[pytest]
testpaths = test_case/UI/Test_Katana
python_files = test_ui.py
addopts = -vs --screenshot="on" --video="on" --headed
norecursedirs = data recordings allure-results allure-report .git .pytest_cache